# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 05:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operacion', '0006_orden_turno'),
        ('subcripcion', '0007_cliente_turnero'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComposicionServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subcripcion.Cuenta')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacion.TipoServicio')),
            ],
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=0)),
                ('composicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.ComposicionServicio')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subcripcion.Cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subcripcion.Cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, max_length=3000, null=True)),
                ('existencias', models.FloatField(default=0)),
                ('stock_minimo', models.FloatField(default=0)),
                ('precio_compra', models.FloatField(verbose_name=0)),
                ('precio_venta', models.FloatField(verbose_name=0)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='operacion',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventario.Producto')),
            ],
            options={
                'verbose_name': 'Producto de operacion',
                'verbose_name_plural': 'Productos de operacion',
            },
            bases=('inventario.producto',),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventario.Producto')),
            ],
            options={
                'verbose_name': 'Producto de venta',
                'verbose_name_plural': 'Productos de venta',
            },
            bases=('inventario.producto',),
        ),
        migrations.AddField(
            model_name='producto',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subcripcion.Cuenta'),
        ),
        migrations.AddField(
            model_name='producto',
            name='presentacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.Presentacion'),
        ),
        migrations.AddField(
            model_name='elemento',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.operacion'),
        ),
    ]
