# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Elemento',
            new_name='Componente',
        ),
    ]
