# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subcripcion', '0007_cliente_turnero'),
        ('inventario', '0003_auto_20181105_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presentacion',
            options={'verbose_name': 'Presentacion', 'verbose_name_plural': 'Presentaciones'},
        ),
        migrations.AlterField(
            model_name='componente',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Operacion'),
        ),
        migrations.AlterField(
            model_name='presentacion',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subcripcion.Cuenta'),
        ),
        migrations.AlterUniqueTogether(
            name='presentacion',
            unique_together=set([('nombre', 'cuenta')]),
        ),
    ]
