# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-06 03:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_auto_20181105_2028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='composicionservicio',
            options={'verbose_name': 'Composicion de Servicio', 'verbose_name_plural': 'Composiciones de Servicios'},
        ),
        migrations.AlterField(
            model_name='componente',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Operacion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_compra',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.FloatField(default=0),
        ),
    ]
