# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-10 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_auto_20181107_0551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componente',
            name='composicion',
        ),
        migrations.RemoveField(
            model_name='componente',
            name='cuenta',
        ),
        migrations.RemoveField(
            model_name='componente',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='composicionservicio',
            name='cuenta',
        ),
        migrations.RemoveField(
            model_name='composicionservicio',
            name='servicio',
        ),
        migrations.DeleteModel(
            name='Componente',
        ),
        migrations.DeleteModel(
            name='ComposicionServicio',
        ),
    ]
