# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-12 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subcripcion', '0008_auto_20181112_2029'),
        ('inventario', '0014_auto_20181110_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cierre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
                ('costo_producto_venta', models.FloatField(default=0, verbose_name='Costo productos de venta')),
                ('utilidad_producto_venta', models.FloatField(default=0, verbose_name='Utilidad productos de venta')),
                ('total_producto_venta', models.FloatField(default=0, verbose_name='Total productos de venta')),
                ('costo_producto_operacion', models.FloatField(default=0, verbose_name='Costo producto operacion')),
                ('utilidad_producto_operacion', models.FloatField(default=0, verbose_name='Utilidad productos de operacion')),
                ('total_producto_operacion', models.FloatField(default=0, verbose_name='Total productos de operacion')),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventario_cierre', to='subcripcion.Cuenta')),
            ],
        ),
    ]
