# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-12 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_auto_20181112_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierre',
            name='costo_producto_operacion',
            field=models.FloatField(default=0, verbose_name='Costo de operacion'),
        ),
        migrations.AlterField(
            model_name='cierre',
            name='costo_producto_venta',
            field=models.FloatField(default=0, verbose_name='Costo de venta'),
        ),
        migrations.AlterField(
            model_name='cierre',
            name='total_producto_operacion',
            field=models.FloatField(default=0, verbose_name='Total de operacion'),
        ),
        migrations.AlterField(
            model_name='cierre',
            name='total_producto_venta',
            field=models.FloatField(default=0, verbose_name='Total de venta'),
        ),
        migrations.AlterField(
            model_name='cierre',
            name='utilidad_producto_operacion',
            field=models.FloatField(default=0, verbose_name='Utilidad de operacion'),
        ),
        migrations.AlterField(
            model_name='cierre',
            name='utilidad_producto_venta',
            field=models.FloatField(default=0, verbose_name='Utilidad de venta'),
        ),
    ]
