# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-15 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_auto_20181112_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
