# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-17 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subcripcion', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total factura')),
                ('comision', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total comisi\xf3n')),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subcripcion.Cuenta')),
            ],
            options={
                'verbose_name': 'Cierre de factura',
                'verbose_name_plural': 'Cierres de facturas',
            },
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(blank=True, default=0.0, null=True)),
                ('comision', models.FloatField(blank=True, default=0.0, null=True)),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subcripcion.Cuenta')),
            ],
            options={
                'verbose_name': 'Cierre dia tipo de servicios',
                'verbose_name_plural': 'Cierres de dias de tipos de servicio',
            },
        ),
    ]
