# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-21 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cierre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total factura')),
                ('comision', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total comisi\xf3n')),
                ('producto', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total producto')),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cierre de turno',
                'verbose_name_plural': 'Cierres de turno',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total factura')),
                ('comision', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total comisi\xf3n')),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
            ],
            options={
                'verbose_name': 'Cierre de factura',
                'verbose_name_plural': 'Cierres de facturas',
            },
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(blank=True, default=0.0, null=True)),
                ('comision', models.FloatField(blank=True, default=0.0, null=True)),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
            ],
            options={
                'verbose_name': 'Cierre dia tipo de servicios',
                'verbose_name_plural': 'Cierres de dias de tipos de servicio',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('inicio', models.TimeField()),
                ('fin', models.TimeField()),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
            },
        ),
    ]
