# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(blank=True, default=0.0, null=True)),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
            ],
            options={
                'verbose_name': 'Cierre de factura',
                'verbose_name_plural': 'Cierres de facturas',
            },
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(blank=True, default=0.0, null=True)),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
            ],
            options={
                'verbose_name': 'Cierre dia tipo de servicios',
                'verbose_name_plural': 'Cierres de dias de tipos de servicio',
            },
        ),
    ]
