# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cierre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='comision',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='tiposervicio',
            name='comision',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
