# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subcripcion', '0002_auto_20170727_0931'),
        ('cierre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subcripcion.Cuenta'),
        ),
        migrations.AddField(
            model_name='tiposervicio',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subcripcion.Cuenta'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total factura'),
        ),
    ]
