# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-20 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cierre', '0001_initial'),
        ('subcripcion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subcripcion.Cuenta'),
        ),
        migrations.AddField(
            model_name='tiposervicio',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subcripcion.Cuenta'),
        ),
        migrations.AddField(
            model_name='factura',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subcripcion.Cuenta'),
        ),
        migrations.AddField(
            model_name='cierre',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subcripcion.Cuenta'),
        ),
        migrations.AddField(
            model_name='cierre',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cierre.Turno'),
        ),
    ]
