# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cierre', '0002_auto_20170727_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='comision',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total comisi\xf3n'),
        ),
        migrations.AddField(
            model_name='tiposervicio',
            name='comision',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
