# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subcripcion', '0003_auto_20170824_1811'),
        ('cierre', '0003_auto_20170727_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('inicio', models.TimeField()),
                ('fin', models.TimeField()),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subcripcion.Cuenta')),
            ],
            options={
                'verbose_name': 'Cierre de turno',
                'verbose_name_plural': 'Cierres de turno',
            },
        ),
    ]
