# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subcripcion', '0003_auto_20170824_1811'),
        ('cierre', '0004_turno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cierre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total factura')),
                ('comision', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total comisi\xf3n')),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subcripcion.Cuenta')),
            ],
            options={
                'verbose_name': 'Cierre de turno',
                'verbose_name_plural': 'Cierres de turno',
            },
        ),
        migrations.AlterModelOptions(
            name='turno',
            options={'verbose_name': 'Turno', 'verbose_name_plural': 'Turnos'},
        ),
        migrations.AddField(
            model_name='cierre',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cierre.Turno'),
        ),
    ]
