# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-18 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cierre', '0008_auto_20181112_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierre',
            name='producto',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total producto'),
        ),
    ]
