# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-11 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_cliente_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipovehiculo',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
