# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-12 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_auto_20181111_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
