# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 21:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_merge_20161006_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='celular',
            field=models.CharField(default=1, max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^([1-9]+[0-9]*){7,20}$'), 'Celular no valida', 'invalid')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(default=1, max_length=200, verbose_name='Correo electr\xf2nico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='dirreccion',
            field=models.CharField(default=11, max_length=300),
            preserve_default=False,
        ),
    ]
