# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-12 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_auto_20181112_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipovehiculo',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
