# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 14:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0012_auto_20161123_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='celular',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(re.compile('^([1-9]+[0-9]*){6,20}$'), 'Celular no valida', 'invalid')]),
        ),
    ]
