# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-30 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subcripcion', '0001_initial'),
        ('cliente', '0013_auto_20161125_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cuenta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_lavadero', to='subcripcion.Cuenta'),
            preserve_default=False,
        ),
    ]
