# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estadistica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiemposorden',
            options={'verbose_name': 'Tiempos de orden', 'verbose_name_plural': 'Tiempos de ordenes'},
        ),
    ]
