# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0027_auto_20161006_1512'),
        ('estadistica', '0002_auto_20161008_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiemposorden',
            name='orden',
        ),
        migrations.AddField(
            model_name='tiemposorden',
            name='orden',
            field=models.ManyToManyField(to='operacion.Orden'),
        ),
    ]
