# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0027_auto_20161006_1512'),
        ('estadistica', '0003_auto_20161009_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiemposorden',
            name='orden',
        ),
        migrations.AddField(
            model_name='tiemposorden',
            name='orden',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='operacion.Orden'),
            preserve_default=False,
        ),
    ]
