# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-22 22:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_auto_20170727_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='identificacion',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(re.compile('^([1-9]+[0-9]*){7,20}$'), 'No valida', 'invalid')]),
        ),
    ]
