# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_auto_20161005_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='fecha_nacimiento',
        ),
    ]
