# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0006_remove_persona_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='nacimiento',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de nacimiento'),
            preserve_default=False,
        ),
    ]
