# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0007_persona_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='nacimiento',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
    ]
