# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-21 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TiemposOrden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
            ],
            options={
                'verbose_name': 'Tiempos de orden',
                'verbose_name_plural': 'Tiempos de ordenes',
            },
        ),
    ]
