# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-12 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subcripcion', '0008_auto_20181112_2029'),
        ('operacion', '0020_auto_20181112_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiemposOrden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tiempo_cuenta', to='subcripcion.Cuenta')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacion.Orden')),
            ],
            options={
                'verbose_name': 'Tiempos de orden',
                'verbose_name_plural': 'Tiempos de ordenes',
            },
        ),
    ]
