# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-21 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estadistica', '0001_initial'),
        ('subcripcion', '0001_initial'),
        ('operacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiemposorden',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tiempo_cuenta', to='subcripcion.Cuenta'),
        ),
        migrations.AddField(
            model_name='tiemposorden',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacion.Orden'),
        ),
    ]
