# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-30 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subcripcion', '0001_initial'),
        ('estadistica', '0004_auto_20161009_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiemposorden',
            name='cuenta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subcripcion.Cuenta'),
            preserve_default=False,
        ),
    ]
