# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-20 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ComposicionServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Composicion de Servicio',
                'verbose_name_plural': 'Composiciones de Servicios',
            },
        ),
        migrations.CreateModel(
            name='HistoriaDeServicioOperacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compra', models.FloatField(default=0)),
                ('cantidad', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaDeServicioVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=0)),
                ('compra', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.DateTimeField(auto_now_add=True, null=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, max_length=1000, null=True)),
                ('valor', models.FloatField(default=0)),
                ('comision', models.FloatField(default=0, verbose_name='Comisi\xf3n')),
                ('cerrada', models.BooleanField(default=False)),
                ('cancelada', models.BooleanField(default=False)),
                ('pago', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('numero', models.IntegerField(default=0)),
                ('turno', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
        migrations.CreateModel(
            name='ProductoVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('total', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Producto a la Venta',
                'verbose_name_plural': 'Productos a la Venta',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(default=0)),
                ('comision', models.FloatField(default=0, verbose_name='comisi\xf3n')),
                ('estado', models.BooleanField(default=False)),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=500, null=True)),
                ('costo', models.FloatField(default=0)),
                ('comision', models.FloatField(default=0, verbose_name='Comisi\xf3n')),
                ('state', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Servicio',
                'verbose_name_plural': 'Tipos de Servicio',
            },
        ),
    ]
