# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-17 17:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
        ('cliente', '0001_initial'),
        ('subcripcion', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.DateTimeField(auto_now_add=True, null=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, max_length=1000, null=True)),
                ('valor', models.FloatField(default=0)),
                ('comision', models.FloatField(default=0, verbose_name='Comisi\xf3n')),
                ('cerrada', models.BooleanField(default=False)),
                ('cancelada', models.BooleanField(default=False)),
                ('pago', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('cajero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cajero', to='empleados.Cajero')),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subcripcion.Cuenta')),
                ('recepcionista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recepcionista', to='empleados.Recepcionista')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.Vehiculo')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(default=0)),
                ('comision', models.FloatField(default=0, verbose_name='comisi\xf3n')),
                ('estado', models.BooleanField(default=False)),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subcripcion.Cuenta')),
                ('operario', models.ManyToManyField(blank=True, to='empleados.Empleado')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operacion.Orden')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500, unique=True)),
                ('costo', models.FloatField(validators=[django.core.validators.RegexValidator(re.compile('^[1-9]+[0-9]*.[0-9]+[0-9]*|[1-9]+[0-9]*$'), 'Costo no valido', 'invalid')])),
                ('comision', models.FloatField(verbose_name='Comisi\xf3n')),
                ('state', models.BooleanField(default=True)),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_ser_cuenta', to='subcripcion.Cuenta')),
                ('vehiculos', models.ManyToManyField(to='cliente.TipoVehiculo')),
            ],
            options={
                'verbose_name': 'Tipo de Servicio',
                'verbose_name_plural': 'Tipos de Servicio',
            },
        ),
        migrations.AddField(
            model_name='servicio',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacion.TipoServicio'),
        ),
    ]
