# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('operacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500, unique=True)),
                ('costo', models.FloatField()),
                ('comision', models.FloatField(verbose_name='Comisi\xf3n')),
                ('state', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Servicio',
                'verbose_name_plural': 'Tipos de Servicio',
            },
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='comision',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='state',
        ),
        migrations.AddField(
            model_name='servicio',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='operacion.TipoServicio'),
            preserve_default=False,
        ),
    ]
