# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-21 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from django.db import migrations, models, connection
import django.db.models.deletion
import os

def load_data_from_sql(apps, schema_editor):
    archivos = os.listdir('/var/www/AutoLavadox/autolavadox/sqls')
    ruta = '/var/www/AutoLavadox/autolavadox/sqls/'
    for file_path in archivos:
        sql_statement = open('{}{}'.format(ruta,file_path)).read()
        with connection.cursor() as c:
            c.execute(sql_statement)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0002_persona_cuenta'),
        ('subcripcion', '0001_initial'),
        ('cliente', '0002_auto_20181121_0333'),
        ('inventario', '0002_auto_20181121_0333'),
        ('operacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposervicio',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_ser_cuenta', to='subcripcion.Cuenta'),
        ),
        migrations.AddField(
            model_name='tiposervicio',
            name='vehiculos',
            field=models.ManyToManyField(blank=True, null=True, to='cliente.TipoVehiculo'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subcripcion.Cuenta'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='operario',
            field=models.ManyToManyField(blank=True, to='empleados.Empleado'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operacion.Orden'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operacion.TipoServicio'),
        ),
        migrations.AddField(
            model_name='productoventa',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subcripcion.Cuenta'),
        ),
        migrations.AddField(
            model_name='productoventa',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operacion.Orden'),
        ),
        migrations.AddField(
            model_name='productoventa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Venta'),
        ),
        migrations.AddField(
            model_name='orden',
            name='cajero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cajero', to='empleados.Cajero'),
        ),
        migrations.AddField(
            model_name='orden',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subcripcion.Cuenta'),
        ),
        migrations.AddField(
            model_name='orden',
            name='recepcionista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recepcionista', to='empleados.Recepcionista'),
        ),
        migrations.AddField(
            model_name='orden',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.Vehiculo'),
        ),
        migrations.AddField(
            model_name='historiadeservicioventa',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacion.Orden'),
        ),
        migrations.AddField(
            model_name='historiadeservicioventa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Venta'),
        ),
        migrations.AddField(
            model_name='historiadeserviciooperacion',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacion.Orden'),
        ),
        migrations.AddField(
            model_name='historiadeserviciooperacion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Operacion'),
        ),
        migrations.AddField(
            model_name='composicionservicio',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subcripcion.Cuenta'),
        ),
        migrations.AddField(
            model_name='composicionservicio',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operacion.TipoServicio', verbose_name='Tipo de Servicio'),
        ),
        migrations.AddField(
            model_name='componente',
            name='composicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operacion.ComposicionServicio'),
        ),
        migrations.AddField(
            model_name='componente',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subcripcion.Cuenta'),
        ),
        migrations.AddField(
            model_name='componente',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.Operacion'),
        ),
        migrations.RunPython(load_data_from_sql),
    ]
