# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-12 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0004_orden_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='operario',
            field=models.ManyToManyField(blank=True, to='empleados.Empleado'),
        ),
    ]
