# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20161004_1057'),
        ('operacion', '0007_auto_20161004_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='cliente',
        ),
        migrations.AddField(
            model_name='servicio',
            name='vehiculo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cliente.Vehiculo'),
            preserve_default=False,
        ),
    ]
