# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-10 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0007_auto_20181110_2001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoventa',
            options={'verbose_name': 'Producto a la Venta', 'verbose_name_plural': 'Productos a la Venta'},
        ),
        migrations.AddField(
            model_name='productoventa',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operacion.Orden'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.Operacion'),
        ),
    ]
