# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20161004_1057'),
        ('operacion', '0010_auto_20161004_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('valor', models.FloatField(default=0)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Vehiculo')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Ordenes',
            },
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='pago',
            new_name='estado',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='vehiculo',
        ),
        migrations.AddField(
            model_name='servicio',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operacion.Orden'),
        ),
    ]
