# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_cajero'),
        ('operacion', '0017_auto_20161005_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='empleado',
        ),
        migrations.AddField(
            model_name='orden',
            name='cajero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cajero', to='empleados.Cajero'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='recepcionista',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recepcionista', to='empleados.Recepcionista'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='operario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operario', to='empleados.Empleado'),
        ),
    ]
