# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0018_auto_20161005_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
