# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_tipovehiculo_descripcion'),
        ('operacion', '0019_auto_20161005_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposervicio',
            name='vehiculos',
            field=models.ManyToManyField(blank=True, null=True, to='cliente.TipoVehiculo'),
        ),
    ]
