# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0023_auto_20161006_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='cajero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cajero', to='empleados.Cajero'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='recepcionista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recepcionista', to='empleados.Recepcionista'),
        ),
    ]
