# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-13 00:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0026_auto_20181112_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.Operacion'),
        ),
        migrations.AlterField(
            model_name='tiposervicio',
            name='costo',
            field=models.FloatField(default=0),
        ),
    ]
