# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0009_auto_20161103_1310'),
        ('operacion', '0028_auto_20161021_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='operario',
        ),
        migrations.AddField(
            model_name='servicio',
            name='operario',
            field=models.ManyToManyField(blank=True, null=True, to='empleados.Empleado'),
        ),
    ]
