# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0029_auto_20161115_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='cerrada',
            field=models.FloatField(null=True),
        ),
    ]
