# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0030_orden_cerrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='operario',
            field=models.ManyToManyField(blank=True, to='empleados.Empleado'),
        ),
    ]
