# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0032_remove_orden_cerrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='cerrada',
            field=models.BooleanField(default=False),
        ),
    ]
