# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0035_orden_cancelada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='observacion',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
