# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-19 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0043_auto_20181118_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiadeserviciooperacion',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='historiadeservicioventa',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='componente',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.Operacion'),
        ),
        migrations.AlterField(
            model_name='historiadeserviciooperacion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Operacion'),
        ),
    ]
