# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-20 07:48
from __future__ import unicode_literals
import os

from autolavadox.settings import BASE_DIR
from django.db import migrations, models, connection
import django.db.models.deletion
from autolavadox.settings import BASE_DIR

def load_data_from_sql(apps, schema_editor):

    archivos = os.listdir(os.path.join(BASE_DIR, 'autolavadox/sqls'))
    for file_path in archivos:
        sql_statement = open(os.path.join(BASE_DIR, 'autolavadox/sqls', file_path)).read()
        with connection.cursor() as c:
            c.execute(sql_statement)

class Migration(migrations.Migration):
    dependencies = [
        ('operacion', '0047_auto_20181120_0748'),
    ]

    operations = [
        migrations.RunPython(load_data_from_sql),
    ]