# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_auto_20161006_1347'),
        ('cliente', '0005_auto_20161006_1208'),
    ]

    operations = [
    ]
