# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_auto_20161101_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipovehiculo',
            name='descripcion',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
