# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500, unique=True)),
                ('costo', models.FloatField()),
                ('comision', models.FloatField(verbose_name='Comisi\xf3n')),
                ('state', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
    ]
