# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0003_servicio_fecha'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servicio',
            new_name='Tarifa',
        ),
    ]
