# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0004_auto_20161004_1102'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tarifa',
            new_name='Servicio',
        ),
    ]
