# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0005_auto_20161004_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='pado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente'),
        ),
    ]
