# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0006_auto_20161004_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='pado',
            new_name='pago',
        ),
    ]
