# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0008_auto_20161004_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='comision',
            field=models.FloatField(default=1, verbose_name='comisi\xf3n'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='valor',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
