# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0009_auto_20161004_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='comision',
            field=models.FloatField(default=0, verbose_name='comisi\xf3n'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='valor',
            field=models.FloatField(default=0),
        ),
    ]
