# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 02:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
        ('operacion', '0011_auto_20161004_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='empleado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empleados.Empleado'),
            preserve_default=False,
        ),
    ]
