# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0012_servicio_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='comision',
            field=models.FloatField(default=0, verbose_name='Comisi\xf3n'),
        ),
    ]
