# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0013_orden_comision'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='entrega',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='pago',
            field=models.BooleanField(default=False),
        ),
    ]
