# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0014_auto_20161004_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='observacion',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
