# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0015_orden_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='entrega',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.Vehiculo'),
        ),
    ]
