# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 18:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0016_auto_20161004_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposervicio',
            name='comision',
            field=models.FloatField(validators=[django.core.validators.RegexValidator(re.compile('^[1-9]+[0-9]{1,2}.[0-9]*|[1-9]+[0-9]{1,2}$'), 'Comisi\xf3n no valida', 'invalid')], verbose_name='Comisi\xf3n'),
        ),
        migrations.AlterField(
            model_name='tiposervicio',
            name='costo',
            field=models.FloatField(validators=[django.core.validators.RegexValidator(re.compile('^[1-9]+[0-9]*.[0-9]+[0-9]*|[1-9]+[0-9]*$'), 'Costo no valido', 'invalid')]),
        ),
    ]
