# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0020_tiposervicio_vehiculos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden',
            old_name='entrega',
            new_name='entreda',
        ),
    ]
