# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0020_tiposervicio_vehiculos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposervicio',
            name='vehiculos',
            field=models.ManyToManyField(to='cliente.TipoVehiculo'),
        ),
    ]
