# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0021_auto_20161006_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='fecha',
        ),
    ]
