# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0024_auto_20161006_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='entrada',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
