# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0025_auto_20161006_1333'),
        ('operacion', '0021_auto_20161006_1347'),
    ]

    operations = [
    ]
