# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0026_merge_20161006_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
