# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0027_auto_20161006_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposervicio',
            name='comision',
            field=models.FloatField(verbose_name='Comisi\xf3n'),
        ),
    ]
