# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-21 03:33
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('identificacion', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^([1-9]+[0-9]*){7,20}$'), 'Identificacion invalida', 'invalid')])),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Direcci\xf3n')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Tel\xe9fono')),
                ('nombre_negocio', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre de la empresa')),
                ('invima', models.CharField(blank=True, max_length=100, null=True, verbose_name='Registro sanitario')),
                ('nit', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nit')),
                ('consecutivo', models.IntegerField(default=0)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/logos/')),
                ('impresora', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre de la impresora')),
                ('reiniciar', models.BooleanField(default=False, verbose_name='Reiniciar serial')),
                ('inventario', models.BooleanField(default=False)),
                ('ventas_sin_existencias', models.BooleanField(default=False, verbose_name='Ventas sin existencias para la operacion')),
                ('turnero', models.IntegerField(default=0, verbose_name='Contador Turnero')),
                ('mostrar_turno', models.BooleanField(default=True, verbose_name='Mostrar turno')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_cuenta', to='subcripcion.Cliente')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(blank=True, max_length=800, null=True)),
                ('operadores', models.IntegerField(default=0, verbose_name='N\xfamero de operadores')),
                ('cajeros', models.IntegerField(default=0, verbose_name='N\xfamero de cajeros')),
                ('recepcionistas', models.IntegerField(default=0, verbose_name='N\xfamero de recepcionistas')),
                ('operario', models.BooleanField(default=True, verbose_name='App empleados')),
                ('gerente', models.BooleanField(default=True, verbose_name='App gerente')),
                ('duracion', models.IntegerField(default=0, verbose_name='Dias de duraci\xf3n en meses')),
                ('valor', models.FloatField(default=0)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscripcion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Inscripci\xf3n')),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subcripcion.Cuenta')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subcripcion.Plan')),
            ],
            options={
                'verbose_name': 'Suscripci\xf3n',
                'verbose_name_plural': 'Suscripciones',
            },
        ),
    ]
