# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcripcion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='consecutivo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cliente',
            name='invima',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Registro sanitario'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/logos/'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nit',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nit'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre_negocio',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre de la empresa'),
        ),
    ]
