# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20170525_2021'),
        ('novedades', '0001_initial'),
        ('admin', '0002_logentry_remove_auto_add'),
        ('operacion', '0003_auto_20170525_2021'),
        ('subcripcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paga', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Suscripci\xf3n',
                'verbose_name_plural': 'Subscripciones',
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscripcion', models.DateTimeField(auto_now_add=True, verbose_name='Inscripci\xf3n')),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Suscripci\xf3n',
                'verbose_name_plural': 'Subscripciones',
            },
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='plan',
            name='asistentes',
            field=models.IntegerField(default=1, verbose_name='N\xfamero de asistentes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='duracion',
            field=models.IntegerField(default=1, verbose_name='Dias de duraci\xf3n en meses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='operadores',
            field=models.IntegerField(default=1, verbose_name='N\xfamero de operadores'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='valor',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subcripcion.Plan'),
        ),
        migrations.AddField(
            model_name='factura',
            name='suscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subcripcion.Suscripcion'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacion.Cliente'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='suscripciones',
            field=models.ManyToManyField(to='subcripcion.Suscripcion'),
        ),
    ]
