# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcripcion', '0002_auto_20170526_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='asistentes',
            field=models.IntegerField(default=0, verbose_name='N\xfamero de asistentes'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='descripcion',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='duracion',
            field=models.IntegerField(default=0, verbose_name='Dias de duraci\xf3n en meses'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='operadores',
            field=models.IntegerField(default=0, verbose_name='N\xfamero de operadores'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='valor',
            field=models.FloatField(default=0),
        ),
    ]
