# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-24 18:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('subcripcion', '0002_auto_20170727_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='impresora',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre de la impresora'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='reiniciar',
            field=models.BooleanField(default=False, verbose_name='Reiniciar serial'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='identificacion',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^([1-9]+[0-9]*){7,20}$'), 'Identificacion invalida', 'invalid')]),
        ),
    ]
