# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcripcion', '0003_auto_20170526_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='instmodulo',
            name='nombre',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
