# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcripcion', '0004_instmodulo_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='instmodulo',
            name='descripcion',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='instmodulo',
            name='nombre',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
