# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcripcion', '0005_auto_20170526_2358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instmodulo',
            options={'verbose_name': 'Modulo plan', 'verbose_name_plural': 'Modulos de planes'},
        ),
        migrations.AddField(
            model_name='factura',
            name='realizacion',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='inscripcion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Inscripci\xf3n'),
        ),
    ]
