# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcripcion', '0006_auto_20181105_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='turnero',
            field=models.IntegerField(default=0, verbose_name='Contador Turnero'),
        ),
    ]
