# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-12 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subcripcion', '0007_cliente_turnero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suscripcion',
            options={'verbose_name': 'Suscripci\xf3n', 'verbose_name_plural': 'Suscripciones'},
        ),
    ]
