# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subcripcion', '0007_auto_20170530_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='telfono',
            new_name='telefono',
        ),
    ]
