# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-15 00:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subcripcion', '0009_auto_20181113_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suscripcion',
            name='estado',
        ),
    ]
