# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-15 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcripcion', '0010_remove_suscripcion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
