# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcripcion', '0010_auto_20170601_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instmodulo',
            name='descripcion',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
