# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subcripcion', '0011_auto_20170601_2307'),
    ]

    operations = [
           ]
