# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-16 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcripcion', '0012_remove_factura_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='mostrar_turno',
            field=models.BooleanField(default=True, verbose_name='Mostrar turno'),
        ),
    ]
