# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-20 02:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subcripcion', '0013_cliente_mostrar_turno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='suscripcion',
        ),
        migrations.RemoveField(
            model_name='funcionalidad',
            name='modulo',
        ),
        migrations.RemoveField(
            model_name='instmodulo',
            name='funcionalidades',
        ),
        migrations.RemoveField(
            model_name='instmodulo',
            name='modulo',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='modulos',
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
        migrations.DeleteModel(
            name='Funcionalidad',
        ),
        migrations.DeleteModel(
            name='InstModulo',
        ),
        migrations.DeleteModel(
            name='Modulo',
        ),
    ]
