# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcripcion', '0014_auto_20170603_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='gerente',
            field=models.BooleanField(default=True, verbose_name='App gerente'),
        ),
        migrations.AddField(
            model_name='plan',
            name='operario',
            field=models.BooleanField(default=True, verbose_name='App empleados'),
        ),
    ]
